version: "3"

services:
  libretranslate:
    container_name: libretranslate
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']     
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,pl
