version: "3"

services:
  libretranslate-cuda:
    container_name: libretranslate-cuda
    build:
      context: .
      dockerfile: docker/cuda.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,pl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
